2024-03-12T10:04:02.2638382+05:30 0HN229MI6T52G:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T10:04:02.4168361+05:30 0HN229MI6T52G:00000001 [INF] Request finished in 306.7637ms 200  (791a596a)
2024-03-12T10:04:34.1395879+05:30 0HN229MI6T52G:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2010 (ca22a1cb)
2024-03-12T10:04:39.1319913+05:30 0HN229MI6T52G:00000002 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 24.8034ms (afa2e885)
2024-03-12T10:04:39.3901266+05:30 0HN229MI6T52G:00000002 [ERR] Connection id ""0HN229MI6T52G"", Request id ""0HN229MI6T52G:00000002"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'InventoryServicesHub.com.vaps.Sales.Interface.ClientInvoiceInterface' while attempting to activate 'InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2024-03-12T10:04:39.4323564+05:30 0HN229MI6T52G:00000002 [INF] Request finished in 5288.096ms 500  (791a596a)
2024-03-12T10:09:38.2366751+05:30 0HN229PMDGTQK:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T10:09:38.3171108+05:30 0HN229PMDGTQK:00000001 [INF] Request finished in 113.9225ms 200  (791a596a)
2024-03-12T10:17:34.1729012+05:30 0HN229U3VSIR5:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T10:17:34.3041425+05:30 0HN229U3VSIR5:00000001 [INF] Request finished in 625.1937ms 200  (791a596a)
2024-03-12T10:56:03.3672982+05:30 0HN22AJKB72OG:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T10:56:03.9126154+05:30 0HN22AJKB72OG:00000001 [INF] Request finished in 631.7775ms 200  (791a596a)
2024-03-12T11:02:51.4457864+05:30 0HN22ANE2585S:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T11:02:51.5435987+05:30 0HN22ANE2585S:00000001 [INF] Request finished in 153.2747ms 200  (791a596a)
2024-03-12T11:27:17.0754265+05:30 0HN22B52QDU0K:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T11:27:17.1908943+05:30 0HN22B52QDU0K:00000001 [INF] Request finished in 274.3451ms 200  (791a596a)
2024-03-12T14:49:50.8497291+05:30 0HN22EM8T0UC5:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T14:49:51.0383339+05:30 0HN22EM8T0UC5:00000001 [INF] Request finished in 347.975ms 200  (791a596a)
2024-03-12T16:41:54.3320512+05:30 0HN22GKSK59GS:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T16:41:54.5085107+05:30 0HN22GKSK59GS:00000001 [INF] Request finished in 267.0079ms 200  (791a596a)
2024-03-12T17:00:22.7316451+05:30 0HN22GV70JFUT:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T17:00:22.8164422+05:30 0HN22GV70JFUT:00000001 [INF] Request finished in 139.8824ms 200  (791a596a)
2024-03-12T17:03:31.5389866+05:30 0HN22H0V771RH:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T17:03:31.7322743+05:30 0HN22H0V771RH:00000001 [INF] Request finished in 353.8754ms 200  (791a596a)
2024-03-12T17:29:49.6895356+05:30 0HN22HFLJTQN4:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T17:29:49.7507454+05:30 0HN22HFLJTQN4:00000001 [INF] Request finished in 123.3654ms 200  (791a596a)
2024-03-12T18:14:46.5481257+05:30 0HN22I8P9QOSJ:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T18:14:46.7272078+05:30 0HN22I8P9QOSJ:00000001 [INF] Request finished in 301.8263ms 200  (791a596a)
2024-03-12T18:16:32.3472729+05:30 0HN22I9OR05VT:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T18:16:32.5189735+05:30 0HN22I9OR05VT:00000001 [INF] Request finished in 268.7988ms 200  (791a596a)
2024-03-12T18:30:04.2671395+05:30 0HN22IHAO1RBA:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T18:30:04.4231722+05:30 0HN22IHAO1RBA:00000001 [INF] Request finished in 253.1495ms 200  (791a596a)
2024-03-12T18:51:32.4084315+05:30 0HN22ITANP53D:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T18:51:32.5556806+05:30 0HN22ITANP53D:00000001 [INF] Request finished in 258.2366ms 200  (791a596a)
2024-03-12T19:06:38.4538943+05:30 0HN22J5OOFFT1:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T19:06:38.5283384+05:30 0HN22J5OOFFT1:00000001 [INF] Request finished in 178.4647ms 200  (791a596a)
2024-03-12T19:09:04.0894593+05:30 0HN22J744J7Q1:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T19:09:04.2348202+05:30 0HN22J744J7Q1:00000001 [INF] Request finished in 207.0714ms 200  (791a596a)
2024-03-12T19:09:50.2478122+05:30 0HN22J744J7Q1:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T19:09:54.5518056+05:30 0HN22J744J7Q1:00000002 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 22.7675ms (afa2e885)
2024-03-12T19:09:54.7424857+05:30 0HN22J744J7Q1:00000002 [ERR] Connection id ""0HN22J744J7Q1"", Request id ""0HN22J744J7Q1:00000002"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'InventoryServicesHub.com.vaps.Sales.Interface.ClientInvoiceInterface' while attempting to activate 'InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2024-03-12T19:09:54.8276663+05:30 0HN22J744J7Q1:00000002 [INF] Request finished in 4576.819ms 500  (791a596a)
2024-03-12T19:10:07.0989819+05:30 0HN22J744J7Q1:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientProformaInvoiceFacade/loaddata application/json 1894 (ca22a1cb)
2024-03-12T19:10:07.1055659+05:30 0HN22J744J7Q1:00000003 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientProformaInvoiceFacade.loaddata (InventoryServicesHub)" in 0.6152ms (afa2e885)
2024-03-12T19:10:07.3050450+05:30 0HN22J744J7Q1:00000003 [ERR] Connection id ""0HN22J744J7Q1"", Request id ""0HN22J744J7Q1:00000003"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'InventoryServicesHub.com.vaps.Sales.Interface.ClientProformaInvoiceInterface' while attempting to activate 'InventoryServicesHub.com.vaps.Sales.Facade.ClientProformaInvoiceFacade'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2024-03-12T19:10:07.3262227+05:30 0HN22J744J7Q1:00000003 [INF] Request finished in 222.9359ms 500  (791a596a)
2024-03-12T19:11:16.5683603+05:30 0HN22J744J7Q2:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T19:11:16.5722500+05:30 0HN22J744J7Q2:00000001 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 0.5548ms (afa2e885)
2024-03-12T19:11:16.6366623+05:30 0HN22J744J7Q2:00000001 [ERR] Connection id ""0HN22J744J7Q2"", Request id ""0HN22J744J7Q2:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'InventoryServicesHub.com.vaps.Sales.Interface.ClientInvoiceInterface' while attempting to activate 'InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2024-03-12T19:11:16.6489758+05:30 0HN22J744J7Q2:00000001 [INF] Request finished in 82.4691ms 500  (791a596a)
2024-03-12T19:12:03.1986185+05:30 0HN22J744J7Q2:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T19:12:03.2098892+05:30 0HN22J744J7Q2:00000002 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 3.1537ms (afa2e885)
2024-03-12T19:12:03.8703859+05:30 0HN22J744J7Q2:00000002 [ERR] Connection id ""0HN22J744J7Q2"", Request id ""0HN22J744J7Q2:00000002"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'InventoryServicesHub.com.vaps.Sales.Interface.ClientInvoiceInterface' while attempting to activate 'InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2024-03-12T19:12:03.9221522+05:30 0HN22J744J7Q2:00000002 [INF] Request finished in 735.6077ms 500  (791a596a)
2024-03-12T19:51:23.6313415+05:30 0HN22J744J7Q3:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T19:51:23.6370205+05:30 0HN22J744J7Q3:00000001 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 1.9551ms (afa2e885)
2024-03-12T19:51:23.7312746+05:30 0HN22J744J7Q3:00000001 [ERR] Connection id ""0HN22J744J7Q3"", Request id ""0HN22J744J7Q3:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'InventoryServicesHub.com.vaps.Sales.Interface.ClientInvoiceInterface' while attempting to activate 'InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2024-03-12T19:51:23.7549508+05:30 0HN22J744J7Q3:00000001 [INF] Request finished in 117.4253ms 500  (791a596a)
2024-03-12T19:52:56.2915501+05:30 0HN22J744J7Q4:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T19:52:56.2938111+05:30 0HN22J744J7Q4:00000001 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 0.591ms (afa2e885)
2024-03-12T19:52:56.3615768+05:30 0HN22J744J7Q4:00000001 [ERR] Connection id ""0HN22J744J7Q4"", Request id ""0HN22J744J7Q4:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'InventoryServicesHub.com.vaps.Sales.Interface.ClientInvoiceInterface' while attempting to activate 'InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2024-03-12T19:52:56.3759505+05:30 0HN22J744J7Q4:00000001 [INF] Request finished in 84.2172ms 500  (791a596a)
2024-03-12T19:56:19.2088105+05:30 0HN22K1H3EEIJ:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T19:56:19.3428910+05:30 0HN22K1H3EEIJ:00000001 [INF] Request finished in 233.4706ms 200  (791a596a)
2024-03-12T19:57:18.9405738+05:30 0HN22K1H3EEIJ:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T19:57:21.7873739+05:30 0HN22K1H3EEIJ:00000002 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 5.0021ms (afa2e885)
2024-03-12T19:57:21.9049986+05:30 0HN22K1H3EEIJ:00000002 [ERR] Connection id ""0HN22K1H3EEIJ"", Request id ""0HN22K1H3EEIJ:00000002"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'InventoryServicesHub.com.vaps.Sales.Interface.ClientInvoiceInterface' while attempting to activate 'InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2024-03-12T19:57:21.9309191+05:30 0HN22K1H3EEIJ:00000002 [INF] Request finished in 2983.8506ms 500  (791a596a)
2024-03-12T20:04:54.5630755+05:30 0HN22K6AKR769:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T20:04:54.7252133+05:30 0HN22K6AKR769:00000001 [INF] Request finished in 237.5424ms 200  (791a596a)
2024-03-12T20:07:49.6546838+05:30 0HN22K7UQ2VDU:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T20:07:49.8701015+05:30 0HN22K7UQ2VDU:00000001 [INF] Request finished in 290.1076ms 200  (791a596a)
2024-03-12T20:09:25.6205455+05:30 0HN22K7UQ2VDV:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T20:09:28.1472744+05:30 0HN22K7UQ2VDV:00000001 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 4.1029ms (afa2e885)
2024-03-12T20:09:28.2437137+05:30 0HN22K7UQ2VDV:00000001 [ERR] Connection id ""0HN22K7UQ2VDV"", Request id ""0HN22K7UQ2VDV:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.InvalidOperationException: Unable to resolve service for type 'InventoryServicesHub.com.vaps.Sales.Interface.ClientInvoiceInterface' while attempting to activate 'InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2024-03-12T20:09:28.2638692+05:30 0HN22K7UQ2VDV:00000001 [INF] Request finished in 2642.4138ms 500  (791a596a)
2024-03-12T20:15:38.7834453+05:30 0HN22KCAJK60T:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T20:15:38.8756025+05:30 0HN22KCAJK60T:00000001 [INF] Request finished in 199.6061ms 200  (791a596a)
2024-03-12T20:16:29.3189853+05:30 0HN22KCPDV7S2:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T20:16:29.6255646+05:30 0HN22KCPDV7S2:00000001 [INF] Request finished in 516.1484ms 200  (791a596a)
2024-03-12T20:17:15.5384539+05:30 0HN22KCPDV7S2:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T20:17:20.5843530+05:30 0HN22KCPDV7S2:00000002 [INF] Entity Framework Core "2.0.3-rtm-10026" initialized '"DomainModelMsSqlServerContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "MigrationsAssembly=WebApplication1 " (9958f5bb)
2024-03-12T20:17:20.8297020+05:30 0HN22KCPDV7S2:00000002 [INF] Executing action method "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" with arguments (["PreadmissionDTOs.com.vaps.Inventory.ClientInvoiceDTO"]) - ModelState is Valid (ba7f4ac2)
2024-03-12T20:17:26.8470680+05:30 0HN22KCPDV7S2:00000002 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2024-03-12T20:17:26.9197555+05:30 0HN22KCPDV7S2:00000002 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 8725.8102ms (afa2e885)
2024-03-12T20:17:26.9332314+05:30 0HN22KCPDV7S2:00000002 [INF] Request finished in 11385.1802ms 200 application/json; charset=utf-8 (791a596a)
2024-03-12T20:18:08.6708049+05:30 0HN22KCPDV7S2:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T20:18:08.6777954+05:30 0HN22KCPDV7S2:00000003 [INF] Entity Framework Core "2.0.3-rtm-10026" initialized '"DomainModelMsSqlServerContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "MigrationsAssembly=WebApplication1 " (9958f5bb)
2024-03-12T20:18:08.7039840+05:30 0HN22KCPDV7S2:00000003 [INF] Executing action method "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" with arguments (["PreadmissionDTOs.com.vaps.Inventory.ClientInvoiceDTO"]) - ModelState is Valid (ba7f4ac2)
2024-03-12T20:24:57.4585144+05:30 0HN22KCPDV7S2:00000003 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2024-03-12T20:24:57.4815483+05:30 0HN22KCPDV7S2:00000003 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 408789.0259ms (afa2e885)
2024-03-12T20:24:57.4925745+05:30 0HN22KCPDV7S2:00000003 [INF] Request finished in 408819.3264ms 200 application/json; charset=utf-8 (791a596a)
2024-03-12T20:26:30.2929141+05:30 0HN22KCPDV7S3:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T20:26:30.2955368+05:30 0HN22KCPDV7S3:00000001 [INF] Entity Framework Core "2.0.3-rtm-10026" initialized '"DomainModelMsSqlServerContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "MigrationsAssembly=WebApplication1 " (9958f5bb)
2024-03-12T20:26:30.2980044+05:30 0HN22KCPDV7S3:00000001 [INF] Executing action method "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" with arguments (["PreadmissionDTOs.com.vaps.Inventory.ClientInvoiceDTO"]) - ModelState is Valid (ba7f4ac2)
2024-03-12T20:29:41.3524826+05:30 0HN22KCPDV7S3:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2024-03-12T20:29:41.3545739+05:30 0HN22KCPDV7S3:00000001 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 191060.0322ms (afa2e885)
2024-03-12T20:29:41.3562167+05:30 0HN22KCPDV7S3:00000001 [INF] Request finished in 191064.3704ms 200 application/json; charset=utf-8 (791a596a)
2024-03-12T20:30:52.4765096+05:30 0HN22KCPDV7S4:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T20:30:52.4808716+05:30 0HN22KCPDV7S4:00000001 [INF] Entity Framework Core "2.0.3-rtm-10026" initialized '"DomainModelMsSqlServerContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "MigrationsAssembly=WebApplication1 " (9958f5bb)
2024-03-12T20:30:52.4869318+05:30 0HN22KCPDV7S4:00000001 [INF] Executing action method "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" with arguments (["PreadmissionDTOs.com.vaps.Inventory.ClientInvoiceDTO"]) - ModelState is Valid (ba7f4ac2)
2024-03-12T20:33:00.2105291+05:30 0HN22KCPDV7S4:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2024-03-12T20:33:00.2160005+05:30 0HN22KCPDV7S4:00000001 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 127734.2476ms (afa2e885)
2024-03-12T20:33:00.2205326+05:30 0HN22KCPDV7S4:00000001 [INF] Request finished in 127743.768ms 200 application/json; charset=utf-8 (791a596a)
2024-03-12T20:33:25.0084180+05:30 0HN22KCPDV7S5:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T20:33:25.0110628+05:30 0HN22KCPDV7S5:00000001 [INF] Entity Framework Core "2.0.3-rtm-10026" initialized '"DomainModelMsSqlServerContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "MigrationsAssembly=WebApplication1 " (9958f5bb)
2024-03-12T20:33:25.0129611+05:30 0HN22KCPDV7S5:00000001 [INF] Executing action method "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" with arguments (["PreadmissionDTOs.com.vaps.Inventory.ClientInvoiceDTO"]) - ModelState is Valid (ba7f4ac2)
2024-03-12T20:33:26.3585188+05:30 0HN22KCPDV7S5:00000001 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2024-03-12T20:33:26.3602568+05:30 0HN22KCPDV7S5:00000001 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 1350.0405ms (afa2e885)
2024-03-12T20:33:26.3638122+05:30 0HN22KCPDV7S5:00000001 [INF] Request finished in 1353.5916ms 200 application/json; charset=utf-8 (791a596a)
2024-03-12T20:33:56.3030080+05:30 0HN22KCPDV7S5:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T20:33:56.3078451+05:30 0HN22KCPDV7S5:00000002 [INF] Entity Framework Core "2.0.3-rtm-10026" initialized '"DomainModelMsSqlServerContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "MigrationsAssembly=WebApplication1 " (9958f5bb)
2024-03-12T20:33:56.3119913+05:30 0HN22KCPDV7S5:00000002 [INF] Executing action method "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" with arguments (["PreadmissionDTOs.com.vaps.Inventory.ClientInvoiceDTO"]) - ModelState is Valid (ba7f4ac2)
2024-03-12T20:45:42.4018034+05:30 0HN22KT46GCFF:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T20:45:42.5662013+05:30 0HN22KT46GCFF:00000001 [INF] Request finished in 166.9395ms 200  (791a596a)
2024-03-12T20:51:44.2683133+05:30 0HN22L0G06A0U:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:50639/  0 (ca22a1cb)
2024-03-12T20:51:44.4254062+05:30 0HN22L0G06A0U:00000001 [INF] Request finished in 191.0559ms 200  (791a596a)
2024-03-12T20:52:29.8816028+05:30 0HN22L0G06A0U:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:50639/api/ClientInvoiceFacade/loaddata application/json 2009 (ca22a1cb)
2024-03-12T20:52:36.6546795+05:30 0HN22L0G06A0U:00000002 [INF] Entity Framework Core "2.0.3-rtm-10026" initialized '"DomainModelMsSqlServerContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "MigrationsAssembly=WebApplication1 " (9958f5bb)
2024-03-12T20:52:36.8739374+05:30 0HN22L0G06A0U:00000002 [INF] Executing action method "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" with arguments (["PreadmissionDTOs.com.vaps.Inventory.ClientInvoiceDTO"]) - ModelState is Valid (ba7f4ac2)
2024-03-12T20:54:40.4545250+05:30 0HN22L0G06A0U:00000002 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2024-03-12T20:54:40.5477952+05:30 0HN22L0G06A0U:00000002 [INF] Executed action "InventoryServicesHub.com.vaps.Sales.Facade.ClientInvoiceFacade.loaddata (InventoryServicesHub)" in 126332.6624ms (afa2e885)
2024-03-12T20:54:40.5504458+05:30 0HN22L0G06A0U:00000002 [INF] Request finished in 130675.5121ms 200 application/json; charset=utf-8 (791a596a)
